FROM python:3.9-slim

EXPOSE 8501
ENV PORT=8501

WORKDIR /frontend
COPY . /frontend

RUN apt-get update && apt-get install -y \
    build-essential \
    software-properties-common \
    git \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install streamlit extractcontent3

ENTRYPOINT ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]