services:
  streamlit:
    build:
      dockerfile: frontend/Dockerfile
    volumes:
      - type: bind
        source: "./frontend"
        target: "/frontend"
    ports:
      - "8501:8501"
  apis:
    build:
      dockerfile: backend/Dockerfile
    volumes:
      - type: bind
        source: "backend"
        target: "/backend"
    ports:
      - "8080:8080"
